name: Update Schedules

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  resolve-schedule-and-upload:
    runs-on: self-hosted-primary

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run Node.js script
      env:  # Pass the secret as an environment variable
        ANIMESCHEDULE_TOKEN: ${{secrets.ANIMESCHEDULE_TOKEN}}
      run: node index.js

    - name: Commit and push JSON files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add './*.json'
        git commit -m "Dubbed airing schedule has changed" || exit 0
        git pull --rebase
        git push