name: Hourly Script Run and JSON Upload

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm i

    - name: Run Node.js script
      env:  # Pass the secret as an environment variable
        ANIMESCHEDULE_TOKEN: ${{secrets.ANIMESCHEDULE_TOKEN}}
      run: node .

    - name: Commit and push JSON files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add './*.json'
        git commit -m "Dubbed airing schedule has changed" || exit 0
        git push